Windows noreturn macro conflict fix
Undefine the noreturn macro while including the tinycthread.h header.
Avoiding this compilation error:

  In file included from C:\projects\taltos\src\eval.c:7:
  In file included from C:\projects\taltos\src/search.h:17:
  In file included from C:\projects\taltos\src/taltos.h:10:
  In file included from C:\projects\taltos\tinycthread\threads.h:1:
  In file included from C:\projects\taltos\tinycthread/tinycthread.h:92:
  In file included from C:\Program Files (x86)\Windows Kits\8.1\Include\um\windows.h:164:
  In file included from C:\Program Files (x86)\Windows Kits\8.1\Include\shared\windef.h:24:
  In file included from C:\Program Files (x86)\Windows Kits\8.1\Include\shared\minwindef.h:182:
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(17675,1): error : __declspec attributes must be an identifier or string literal [C:\projects\taltos\build\taltos_code.vcxproj]
  DECLSPEC_NORETURN
  ^
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(182,40):  note: expanded from macro 'DECLSPEC_NORETURN'
  #define DECLSPEC_NORETURN   __declspec(noreturn)
                                         ^
  C:\Program Files\LLVM\msbuild-bin\..\lib\clang\4.0.0\include\stdnoreturn.h(27,18):  note: expanded from macro 'noreturn'
  #define noreturn _Noreturn
                   ^